name: lightmedchain
description: Lightweight Blockchain Medical Record System

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  go_router: ^12.1.3
  json_annotation: ^4.8.1
  charts_flutter: ^0.12.0  # ← VERSİYON DÜŞÜRÜLDÜ
  fl_chart: ^1.1.1 
  flutter_blue_plus: ^1.14.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true